### ISSUE TITLE
sso portal redirects back to the portal

### ISSUE THREAD

**Issue by ballinger** [YunoHost-Apps/superset_ynh#7]
### Describe the bug

sso portal redirects back to the portal

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: latest
- I have access to my server: yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: testing
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- install testing branch
- open url

### Expected behavior
open superset webpage

**Comment by tituspijean** [comment]
Fixed by #8
